### ISSUE TITLE
Uploading `dops` to package managers

### ISSUE THREAD

**Issue by kpalang** [Mikescher/better-docker-ps#1]
Hello!

First of all, thank you for this tool! I absolutely love it! It makes quickly grasping `docker ps` so much easier that looking at it's output is pure pleasure.

I've a question/suggestion.
Would you be interested in uploading `dops` to package managers? I personally would be interested in AUR entries.

Thanks

**Comment by Mikescher** [comment]
good idea,

I created two packages:
 - https://aur.archlinux.org/packages/dops-bin
 - https://aur.archlinux.org/packages/dops-git
