### ISSUE TITLE
Add options to buy the author a beer

### ISSUE THREAD

**Issue by kpalang** [Mikescher/better-docker-ps#10]
I today realized that this tool has become a must have for me and looking at regular `docker ps` is painful. Thus, I would like to buy you a beer or two.

Please provide a way for me to do so :slightly_smiling_face:

**Comment by Mikescher** [comment]
Thanks :D

If you really want there is a [buymeabeer](https://www.buymeacoffee.com/Mikescher) link in my github profile.

But honestly I mostly made that tool for myself, and this issue makes me probably more happy than any donation.  
It's just nice knowing that dops is actually used somewhere else (than by me and my direct colleagues).  

*(I wish github had a download counter :D)*
