### ISSUE TITLE
Option parsing of docker ps command is incorrect with concatenated option flags

### ISSUE THREAD

**Issue by krishnakumarg1984** [Mikescher/better-docker-ps#3]
If we pass more option flags to the `docker ps` command in the concatenated short-form style, e.g. `docker ps -aq` where the `-q` flag is concatenated with the `-a` flag to result in the combined `-aq` flag, we do not get the correct output from `dops`.

As an example, if we have the following situation
```
$ docker ps -a
CONTAINER ID   IMAGE     COMMAND                  CREATED         STATUS                     PORTS     NAMES
030aa141e0bc   nginx     "/docker-entrypoint.…"   4 minutes ago   Exited (0) 3 minutes ago             website
```

`dops -a`  works absolutely fine.
```
$ dops -a
CONTAINER ID    NAME       IMAGE    TAG    CREATED AT (+01:00 BST)    STATE       STATUS                      PUBLISHED PORTS
------------    -------    -----    ---    -----------------------    --------    ------------------------    ---------------
030aa141e0bc    website    nginx           2023-05-18 16:00:36        [EXITED]    Exited (0) 4 minutes ago
```

while, the `-aq` combined flag does not produce the correct output. With `docker ps -aq`, we get the container ID as expected i.e. `030aa141e0bc`. 

However, `dops -aq` produces an empty output. The long form,  `dops -a -q` does work correctly though.  The bash/zsh/fish alias functions are also correspondingly broken.

**Comment by Mikescher** [comment]
Yeah, I guess the commandline parser currently does not pick up the short syntax - I'll try to look into it next week
