### ISSUE TITLE
Feature: Sorting by column

### ISSUE THREAD

**Issue by jordantrizz** [Mikescher/better-docker-ps#4]
Looked around, couldn't find anything that would allow sorting by column. Specifically container name, alphabetical would be great to easily locate a container.

**Comment by Mikescher** [comment]
Hmm good idea, shouldn't be too hard, I'll look into it next week.  
But if you want you can also send me a PR

**Comment by jordantrizz** [comment]
Would love to, but I haven't tackled go as a programming language yet :(

**Comment by Mikescher** [comment]
I have a [buymeacoffee](https://www.buymeacoffee.com/Mikescher) link in my github profile, but you don't have to sponsor me or anything - I do it mostly for fun and giving back the community ^^

**Comment by jordantrizz** [comment]
If you make my day easier, then you deserve a coffee :)
