### ISSUE TITLE
arm support (32bit)?

### ISSUE THREAD

**Issue by b1n4ryj4n** [Mikescher/better-docker-ps#7]
Hi there,
is it possible to add arm support (32bit) for Raspberry Pi 3?

**Comment by Mikescher** [comment]
Sure, I updated the Makefile and added the binaries to the latest release: https://github.com/Mikescher/better-docker-ps/releases/tag/v1.11

Can you try the arm32v5 binary?, I currently do not have a raspberry-3 with docker lying around

**Comment by b1n4ryj4n** [comment]
thanks! it works.
